#!/bin/bash
[user]
	email = bsai2020@gmail.com
	name = BhargavaSai

[branch]
	autosetuprebase = always
[color]
	ui = true
	status = auto
	branch = auto
[core]
	editor = vim
[commit]
	template = /home/bhargava/.gitmessage

